#! /bin/sh

bspc config border_width      2.3 
bspc config window_gap         14
bspc config top_padding        45 
bspc config bottom_padding     45
bspc config left_padding       45
bspc config right_padding      45

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color "#05404f"
bspc config active_border_color "#04323e"
bspc config normal_border_color "#04323e"
bspc config urgent_border_color "#cf9f3f"

bspc config pointer_follows_monitor true

bspc monitor DVI-I-1 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

# Custom padding second monitor
bspc config -d ^6 top_padding -30
bspc config -d ^6 bottom_padding -30
bspc config -d ^6 left_padding -30
bspc config -d ^6 right_padding -30

bspc config -d ^7 top_padding -30
bspc config -d ^7 bottom_padding -30
bspc config -d ^7 left_padding -30
bspc config -d ^7 right_padding -30

bspc config -d ^8 top_padding -30
bspc config -d ^8 bottom_padding -30
bspc config -d ^8 left_padding -30
bspc config -d ^8 right_padding -30

bspc config -d ^9 top_padding -30
bspc config -d ^9 bottom_padding -30
bspc config -d ^9 left_padding -30
bspc config -d ^9 right_padding -30

bspc config -d ^10 top_padding -30
bspc config -d ^10 bottom_padding -30
bspc config -d ^10 left_padding -30
bspc config -d ^10 right_padding -30

bspc rule -a Screenkey manage=off

# Floating
bspc rule -a Thunar floating=on
bspc rule -a Deluge floating=on 
bspc rule -a Skype  floating=on desktop=^7

# Wallpaper
hsetroot -solid '#001E26'
# nitrogen --restore &

# Composing
compton --config ~/.config/bspwm/.compton.conf &

# Bar
. ~/.config/bspwm/bar.sh | bar -B '#001E26FF' -d -p -g 1800x20+60+21 -f "-*-droid sans mono-medium-r-*-*-11-*-*-*-*-*-*-*" 
 &
